steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/contact-repo/contact-app'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/contact-repo/contact-app'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'contact-app-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/contact-repo/contact-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'cloud-deploy-481317:us-central1:contact-db'
      - '--set-secrets'
      - 'DATABASE_URL=projects/$PROJECT_ID/secrets/DATABASE_URL:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/contact-repo/contact-app'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
